@url = http://localhost:8080

###
GET {{url}}/dev/seed

###

GET {{url}}/users

###
GET {{url}}/users/2

###
GET {{url}}/users/seed

###
GET {{url}}/

###

GET {{url}}/users
x-auth-Token: 1234

###
GET {{url}}/products?categoryId=1

###
GET {{url}}/products/1

###
POST {{url}}/users
Content-Type: application/json

{
  "email": "1123-1018@example.com",
  "name": "asd",
  "password": "pw1234"
}

###
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "1123-1018@example.com",
  "password": "pw1234"
}

###
POST {{url}}/auth/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMTIzLTEwMThAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjM5MDQ0NjEsImV4cCI6MTc2Mzk5MDg2MX0.-JyFs_GPMom92lQzd7pt78V1HhTpiR4HDkAR7mJga6I

###
GET {{url}}/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMTIzLTEwMThAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjM5MDQ0NjEsImV4cCI6MTc2Mzk5MDg2MX0.-JyFs_GPMom92lQzd7pt78V1HhTpiR4HDkAR7mJga6I

###
PUT {{url}}/users/100
Content-Type: application/json

{
  "email": "joe@example.com",
  "name": "Joe"
}

###
DELETE {{url}}/users/1

###
POST {{url}}/users/4/change-password
Content-Type: application/json

{
  "oldPassword": "pw1234",
  "newPassword": "5678"
}