@url = http://localhost:8080

###
GET {{url}}/dev/seed

###

GET {{url}}/users

###
GET {{url}}/users/2

###
GET {{url}}/users/seed

###
GET {{url}}/

###

GET {{url}}/users
x-auth-Token: 1234

###
GET {{url}}/products?categoryId=1

###
GET {{url}}/products/1

###
POST {{url}}/users
Content-Type: application/json

{
  "email": "1123-1716@example.com",
  "name": "asd",
  "password": "pw1234"
}

###
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "1123-1716@example.com",
  "password": "pw1234"
}

###
GET {{url}}/admin/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNCIsImVtYWlsIjoiMTEyMy0xNzE2QGV4YW1wbGUuY29tIiwibmFtZSI6ImFzZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc2MzkxNTQzMCwiZXhwIjoxNzYzOTQ1NDMwfQ.gZo7_C0nB0lDqwRSsk5ZrzzkKopwBSjgiY22DA8y870


###
POST {{url}}/auth/refresh

###
GET {{url}}/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMyIsImVtYWlsIjoiMTEyMy0xMDE4QGV4YW1wbGUuY29tIiwibmFtZSI6ImFzZCIsImlhdCI6MTc2MzkxMjc5MSwiZXhwIjoxNzYzOTEzMDkxfQ.oeC4M45gJOINoXk4Mwm4Sc7NlbSsSUEj5PENIIv2Em4

###
PUT {{url}}/users/100
Content-Type: application/json

{
  "email": "joe@example.com",
  "name": "Joe"
}

###
DELETE {{url}}/users/1

###
POST {{url}}/users/4/change-password
Content-Type: application/json

{
  "oldPassword": "pw1234",
  "newPassword": "5678"
}