@url = http://localhost:8080
@cartId = 48c2341e-fecc-42cb-bb4a-94b89cf406a5

###
POST {{url}}/carts

###
POST {{url}}/carts/{{cartId}}/items
Content-Type: application/json

{
  "productId": 5
}

###
PUT {{url}}/carts/{{cartId}}/items/2
Content-Type: application/json

{
  "quantity": 2
}


###
GET {{url}}/carts/{{cartId}}

###
DELETE {{url}}/carts/{{cartId}}/items/2

###

DELETE {{url}}/carts/{{cartId}}/items
